//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.13 at 04:11:17 AM EEST
//

package com.birkle.hatef.web.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.birkle.hatef.web.soap package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.birkle.hatef.web.soap
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostVehiclesRequest }
     */
    public PostVehiclesRequest createPostVehiclesRequest() {
        return new PostVehiclesRequest();
    }

    /**
     * Create an instance of {@link VehicleDetails }
     */
    public VehicleDetails createVehicleDetails() {
        return new VehicleDetails();
    }

    /**
     * Create an instance of {@link PostVehiclesResponse }
     */
    public PostVehiclesResponse createPostVehiclesResponse() {
        return new PostVehiclesResponse();
    }
}
