//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.13 at 04:11:17 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.web.hatef.birkle.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.birkle.hatef.web.soap;
