//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.13 at 04:11:17 AM EEST
//

package com.birkle.hatef.web.soap;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VehicleDetails" type="{http://soap.web.hatef.birkle.com}VehicleDetails" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicleDetails"
})
@XmlRootElement(name = "postVehiclesResponse")
public class PostVehiclesResponse {

    @XmlElement(name = "VehicleDetails", required = true)
    protected List<VehicleDetails> vehicleDetails;

    /**
     * Gets the value of the vehicleDetails property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicleDetails property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicleDetails().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleDetails }
     */
    public List<VehicleDetails> getVehicleDetails() {
        if (vehicleDetails == null) {
            vehicleDetails = new ArrayList<VehicleDetails>();
        }
        return this.vehicleDetails;
    }
}
