//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.13 at 04:11:17 AM EEST
//

package com.birkle.hatef.web.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.time.LocalDate;


/**
 * <p>Java class for VehicleDetails complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VehicleDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plateCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plateNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manufacturedCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleDetails", propOrder = {
    "brand",
    "model",
    "plateCountry",
    "vehicleType",
    "plateNumber",
    "vin",
    "creationDate",
    "manufacturedCountry"
})
public class VehicleDetails {

    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected String plateCountry;
    @XmlElement(required = true)
    protected String vehicleType;
    @XmlElement(required = true)
    protected String plateNumber;
    @XmlElement(required = true)
    protected String vin;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate creationDate;
    @XmlElement(required = true)
    protected String manufacturedCountry;

    /**
     * Gets the value of the brand property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the model property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the plateCountry property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPlateCountry() {
        return plateCountry;
    }

    /**
     * Sets the value of the plateCountry property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPlateCountry(String value) {
        this.plateCountry = value;
    }

    /**
     * Gets the value of the vehicleType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVehicleType(String value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the plateNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * Sets the value of the plateNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPlateNumber(String value) {
        this.plateNumber = value;
    }

    /**
     * Gets the value of the vin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVin() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVin(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public LocalDate getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCreationDate(LocalDate value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the manufacturedCountry property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getManufacturedCountry() {
        return manufacturedCountry;
    }

    /**
     * Sets the value of the manufacturedCountry property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setManufacturedCountry(String value) {
        this.manufacturedCountry = value;
    }
}
